name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global vercel@latest
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: websites/bijbelquiz.app
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

  deploy-backend:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global vercel@latest
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: websites/backend.bijbelquiz.app
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

  deploy-status:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global vercel@latest
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: websites/status.bijbelquiz.app
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STATUS }}
